version: '3.3'

services:
    my_mongodb:
     image: mongo:4.0.4
     volumes:
       - data_volume:/data/db
     restart: always

    book_store:
     depends_on:
       - my_mongodb
     image: siyongdocker/springmongodocker:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       SPRING_DATA_MONGODB_HOST: 'my_mongodb' #Overwrite spring.data.mongodb.host in springboot application.property
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8080/health"] 
       interval: 20s
       timeout: 8s
       retries: 3
           
volumes:
    data_volume: 